apiVersion: v1
kind: Template
metadata:
  name: osiris-observer-buildconfig
  annotations:
    description: >
      This is Osiris Observer BuildConfig Template.
    openshift.io/display-name: 'Thoth: Osiris Observer - BuildConfig'
    tags: ai-stacks,aistacks,build,build-aggregator,build-analysis,thoth,osiris,osiris-observer
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Osiris Observer BuildConfig Template.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: osiris-observer-buildonfig
    app: osiris
    component: osiris-observer

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      labels:
        app: osiris
        component: osiris-observer
      name: osiris-observer
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: osiris-observer:latest
      postCommit: {}
      resources: {}
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python:latest
            namespace: openshift
      triggers:
      - type: GitHub
        github:
          secret: "osiris-observer-build-trigger"
      - type: ConfigChange
      - type: ImageChange
        automatic: {}

parameters:
  - description: Name of the github repository for Thoth's Osiris Observer
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/osiris-build-observer'

  - description: Git reference to be used for Thoth's Osiris Observer
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'
